inherit_from: .rubocop_todo.yml

# Turn on RSpec cops
require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'Gemfile.lock'
    - '**/*.md'
    - 'bin/**/*'
    - 'lib/**/*.rake'
    - 'vendor/**/*' # avoid running rubocop on travis cached bundler
  SuggestExtensions: false

Lint/UselessAssignment:
  Exclude:
    - 'lib/moab/storage_repository.rb' # TODO: determine if we want to keep this exclusion
    - 'lib/moab/storage_services.rb' # TODO: determine if we want to keep this exclusion
    - 'lib/serializer/serializable.rb' # TODO: determine if we want to keep this exclusion
    - 'spec/features/stanford/content_metadata_read_spec.rb' # TODO: determine if we want to keep this exclusion
    - 'spec/unit_tests/moab/file_group_difference_spec.rb' # TODO: determine if we want to keep this exclusion
    - 'spec/unit_tests/moab/file_group_spec.rb' # TODO: determine if we want to keep this exclusion
    - 'spec/unit_tests/moab/file_inventory_spec.rb' # TODO: determine if we want to keep this exclusion

Metrics/ClassLength:
  Exclude:
    - lib/moab/deposit_bag_validator.rb # it's long but splitting it would make it worse

# because this isn't 1994
Layout/LineLength:
  Max: 130 # would like to reduce this to 120
  Exclude:
    - lib/moab/deposit_bag_validator.rb # line 167
    - 'lib/moab/file_manifestation.rb'
    - lib/moab/storage_object_validator.rb # long interpolated error message line
    - 'spec/unit_tests/moab/file_group_difference_spec.rb' # remove after PR #50 merged
    - 'spec/unit_tests/moab/storage_object_validator_spec.rb'
    - 'spec/unit_tests/stanford/storage_object_validator_spec.rb'

# Code was readable with allowing higher perceived complexity
Metrics/PerceivedComplexity:
  Max: 13

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'moab-versioning.gemspec'

RSpec/NestedGroups:
  Exclude:
    - spec/unit_tests/moab/deposit_bag_validator_spec.rb # tests are readable
    - spec/unit_tests/moab/storage_object_validator_spec.rb # Tests are more readable, all the tests should be under 1 context block
    - spec/unit_tests/stanford/storage_object_validator_spec.rb # tests are readable

# Pointless change
Style/FormatStringToken:
  Enabled: false

# Loops were easier to understand without using 'next' statement
Style/Next:
  Enabled: false

# because ' vs " isn't a big deal for readability or maintainability or execution time
Style/StringLiterals:
  Enabled: false

Style/ZeroLengthPredicate:
  Exclude:
    - 'lib/moab/bagger.rb' # is calling `x.size == 0` on Pathname objects, which don't have `.empty?` on old Rubies

Layout/SpaceBeforeBrackets: # (new in 1.7)
  Enabled: true
Lint/AmbiguousAssignment: # (new in 1.7)
  Enabled: true
Lint/DuplicateBranch: # (new in 1.3)
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true
Lint/EmptyBlock: # (new in 1.1)
  Enabled: true
Lint/EmptyClass: # (new in 1.3)
  Enabled: true
Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: true
Lint/ToEnumArguments: # (new in 1.1)
  Enabled: true
Lint/UnexpectedBlockArity: # (new in 1.5)
  Enabled: true
Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true
Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: true
Style/CollectionCompact: # (new in 1.2)
  Enabled: true
Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: true
Style/HashExcept: # (new in 1.7)
  Enabled: true
Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: true
Style/NilLambda: # (new in 1.3)
  Enabled: true
Style/RedundantArgument: # (new in 1.4)
  Enabled: true
Style/SwapValues: # (new in 1.1)
  Enabled: true
