inherit_from: .rubocop_todo.yml

# Turn on RSpec cops
require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Include:
    - 'Rakefile'
  Exclude:
    - 'Gemfile.lock'
    - '**/*.md'
    - 'bin/**/*'
    - 'lib/**/*.rake'
    - 'vendor/**/*' # avoid running rubocop on travis cached bundler

# --- Layout ---

# --- Lint ---

# --- Metrics ---

# because this isn't 1994
Metrics/LineLength:
  Max: 130 # would like to reduce this to 120
  Exclude:
    - 'lib/moab/file_manifestation.rb'
    - 'spec/unit_tests/moab/bagger_spec.rb' # remove after PR #52 merged
    - 'spec/unit_tests/moab/file_group_difference_spec.rb' # remove after PR #50 merged

# --- Naming ---

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'moab-versioning.gemspec'

# -- Performance ---

# --- RSpec ---

# --- Style ---

# because ' vs " isn't a big deal for readability or maintainability or execution time
Style/StringLiterals:
  Enabled: false

# because annotated tokens didn't work
Style/FormatStringToken:
  Enabled: false
