version: 2.1
orbs:
  ruby-rails: sul-dlss/ruby-rails@4.5.0
workflows:
  build:
    jobs:
      - ruby-rails/lint-gem:
          name: lint
      - ruby-rails/test-gem:
          name: test
          context: dlss
          use-codecov: true
